# Generated by Django 2.2.20 on 2021-06-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='摂氏')),
                ('humidity', models.IntegerField(verbose_name='湿度')),
                ('illumination', models.IntegerField(verbose_name='湿度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='取得日時')),
            ],
        ),
    ]
