# Generated by Django 2.2.20 on 2021-06-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalue',
            name='illumination',
            field=models.IntegerField(verbose_name='照度'),
        ),
    ]
